"""
==============================================================================
Interview Plan

Purpose:
Represents the execution plan for an interview.

Generated by the Interview Planner.

Contains all interview phases in execution order.

==============================================================================
"""

from pydantic import BaseModel, Field

from app.schemas.interview_engine.interview_phase import (
    InterviewPhase,
)


class InterviewPlan(BaseModel):
    """
    Complete interview execution plan.
    """

    phases: list[InterviewPhase] = Field(
        default_factory=list
    )

    total_duration_minutes: int = Field(
        gt=0
    )