"""
==============================================================================
Interview Objective

Purpose:
Represents one thing the interviewer wants to evaluate.

Examples:

- Python
- FastAPI
- Docker
- Resume Project
- Communication
- Problem Solving

Objectives are generated by the Interview Planner.

The Interview Orchestrator marks them as completed
during the interview.

This is a runtime domain model.
It is NOT stored directly in the database.
==============================================================================
"""

from pydantic import BaseModel, Field


class InterviewObjective(BaseModel):
    """
    One interview objective.
    """

    name: str = Field(
        description="Objective name."
    )

    description: str = Field(
        description="What this objective evaluates."
    )

    priority: int = Field(
        ge=1,
        le=10,
        description="Importance of this objective."
    )

    completed: bool = False