"""create interview answers table

Revision ID: 02e119cac187
Revises: f0f592e2c169
Create Date: 2026-06-19 10:03:57.575887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e119cac187'
down_revision: Union[str, Sequence[str], None] = 'f0f592e2c169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_session_id', sa.Integer(), nullable=False),
    sa.Column('interview_question_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('answer_source', sa.Enum('TEXT', 'VOICE', name='answersource'), nullable=False),
    sa.Column('answer_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_question_id'], ['interview_questions.id'], ),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_answers')
    # ### end Alembic commands ###
