"""add_answer_evaluations

Revision ID: 3b9580228d87
Revises: d43422b04a8a
Create Date: 2026-07-20 19:30:51.358934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b9580228d87'
down_revision: Union[str, Sequence[str], None] = 'd43422b04a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_answer_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('keyword_coverage', sa.Float(), nullable=False),
    sa.Column('concept_coverage', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('vocabulary_statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammar_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('readability_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('semantic_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('communication_clarity', sa.String(), nullable=True),
    sa.Column('communication_confidence', sa.String(), nullable=True),
    sa.Column('communication_tone', sa.String(), nullable=True),
    sa.Column('communication_feedback', sa.String(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_evaluations')
    # ### end Alembic commands ###
