"""Add JSONB AI profile data

Revision ID: 90113a0a09f2
Revises: c1e2f3a4b5d6
Create Date: 2026-07-14 12:44:55.792147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90113a0a09f2'
down_revision: Union[str, Sequence[str], None] = 'c1e2f3a4b5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_provider', postgresql.ENUM('LOCAL', 'S3', 'AZURE', 'GCS', name='storageprovider', create_type=False), server_default='LOCAL', nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('upload_status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='uploadstatus', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('parsing_status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED', name='parsingstatus', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Persisted JSON payload of the extracted JobProfile aggregate.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.add_column('resumes', sa.Column('candidate_profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Persisted JSON payload of the extracted CandidateProfile aggregate.'))
    op.alter_column('resumes', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='Filename as provided by the user at upload time.',
               existing_nullable=False)
    op.alter_column('resumes', 'stored_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='UUID-based filename used on the storage layer.',
               existing_nullable=False)
    op.alter_column('resumes', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               comment="Canonical file extension, e.g. '.pdf' or '.docx'.",
               existing_nullable=False)
    op.alter_column('resumes', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment='MIME type of the uploaded file (e.g. application/pdf).',
               existing_nullable=False)
    op.alter_column('resumes', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               comment='File size in bytes.',
               existing_nullable=False)
    op.alter_column('resumes', 'storage_provider',
               existing_type=postgresql.ENUM('LOCAL', 'S3', 'AZURE', 'GCS', name='storageprovider'),
               comment='Which storage backend holds this file.',
               existing_nullable=False,
               existing_server_default=sa.text("'LOCAL'::storageprovider"))
    op.alter_column('resumes', 'storage_path',
               existing_type=sa.TEXT(),
               comment='Provider-agnostic logical path used by StorageBackend. For local storage: relative path from STORAGE_LOCAL_ROOT. For S3: object key.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'storage_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Provider-agnostic logical path used by StorageBackend. For local storage: relative path from STORAGE_LOCAL_ROOT. For S3: object key.',
               existing_nullable=False)
    op.alter_column('resumes', 'storage_provider',
               existing_type=postgresql.ENUM('LOCAL', 'S3', 'AZURE', 'GCS', name='storageprovider'),
               comment=None,
               existing_comment='Which storage backend holds this file.',
               existing_nullable=False,
               existing_server_default=sa.text("'LOCAL'::storageprovider"))
    op.alter_column('resumes', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='File size in bytes.',
               existing_nullable=False)
    op.alter_column('resumes', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='MIME type of the uploaded file (e.g. application/pdf).',
               existing_nullable=False)
    op.alter_column('resumes', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="Canonical file extension, e.g. '.pdf' or '.docx'.",
               existing_nullable=False)
    op.alter_column('resumes', 'stored_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UUID-based filename used on the storage layer.',
               existing_nullable=False)
    op.alter_column('resumes', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Filename as provided by the user at upload time.',
               existing_nullable=False)
    op.drop_column('resumes', 'candidate_profile_data')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
