"""Add foreign keys to InterviewSession

Revision ID: 9b2bf41d3a41
Revises: 90113a0a09f2
Create Date: 2026-07-14 16:55:45.054101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2bf41d3a41'
down_revision: Union[str, Sequence[str], None] = '90113a0a09f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('job_description_id', sa.Integer(), nullable=True))
    op.execute("UPDATE interview_sessions SET job_description_id = CAST(job_description AS INTEGER) WHERE job_description ~ '^[0-9]+$'")
    op.create_foreign_key(None, 'interview_sessions', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'interview_sessions', 'job_descriptions', ['job_description_id'], ['id'], ondelete='SET NULL')
    op.drop_column('interview_sessions', 'job_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'job_description_id')
    # ### end Alembic commands ###
