"""remove education and target_role from profiles

Revision ID: b9758a2d75da
Revises: f079a2ceb3e0
Create Date: 2026-06-16 20:33:33.282797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9758a2d75da'
down_revision: Union[str, Sequence[str], None] = 'f079a2ceb3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'target_role')
    op.drop_column('profiles', 'education')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('education', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('target_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
