"""Add execution_path to interview_questions

Revision ID: d43422b04a8a
Revises: 9b2bf41d3a41
Create Date: 2026-07-19 20:41:30.656625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43422b04a8a'
down_revision: Union[str, Sequence[str], None] = '9b2bf41d3a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('planned_order', sa.Integer(), nullable=True))
    op.add_column('interview_questions', sa.Column('execution_path', sa.String(), nullable=True))
    
    # Data migration: backfill new columns from existing question_order
    op.execute(
        "UPDATE interview_questions SET planned_order = question_order, "
        "execution_path = LPAD(CAST(question_order AS VARCHAR), 2, '0')"
    )
    
    op.alter_column('interview_questions', 'planned_order', nullable=False)
    op.alter_column('interview_questions', 'execution_path', nullable=False)
    
    op.create_index(op.f('ix_interview_questions_execution_path'), 'interview_questions', ['execution_path'], unique=False)
    op.drop_column('interview_questions', 'question_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('question_order', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Reverse data migration
    op.execute(
        "UPDATE interview_questions SET question_order = planned_order"
    )
    
    op.alter_column('interview_questions', 'question_order', nullable=False)
    
    op.drop_index(op.f('ix_interview_questions_execution_path'), table_name='interview_questions')
    op.drop_column('interview_questions', 'execution_path')
    op.drop_column('interview_questions', 'planned_order')
    # ### end Alembic commands ###
